import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '../componentes/Button'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div>
          <h1 className='font-bold text-2xl'>Oi, alguem.</h1>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore, quas provident! Nostrum quo error necessitatibus ipsam tempora ratione numquam non, architecto, quasi maxime ipsum odit. Libero autem, excepturi nulla reiciendis repellat vitae eum, quia perspiciatis delectus ab fugiat et. Necessitatibus nisi, accusantium consequuntur nesciunt voluptates ipsa qui distinctio molestiae itaque!</p>

          <Button disabled={true}>Clicar</Button>

          <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam beatae quas mollitia nam praesentium sit earum, laboriosam tenetur cupiditate libero rerum veniam at laudantium nostrum maiores eius cum autem est aut consectetur nemo nisi a! Cum, delectus animi maiores dolore nisi ut quis adipisci. In voluptas deleniti eligendi voluptates officiis.</p>

          <Button>Clicar de novo</Button> 

        </div>
      </main>

   
    </div>
  )
}

export default Home
